name: DS5111 Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    name: Code Quality Inspector (Linter)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check Python Version
      run: |
        python --version

    - name: Install pipeline dependencies
      run: |
        make -C scripts update

    - name: Run Code Quality Checks
      run: |
        make -C scripts lint


  test:
    name: Unit Testing Engine (Pytest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check Python Version
      run: |
        python --version

    - name: Install pipeline dependencies
      run: |
        make -C scripts update

    - name: Run Complete Test Engine Suite
      run: |
        make -C scripts test
